baseurl = "http://www.staphb.org"
title = "StaPH-B"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = ""
    info = "The State Public Health Bioinformatics Group (StaPH-B) is a consortium of public health scientists interested in addressing the common barriers impeding bioinformatics implementation in state public health laboratories."
    description = "StaPH-B Training Website"
    keywords = "bioinformatics, public health, infectious disease"
    avatarurl = "images/staphb-logo.png"

    favicon_32 = "/img/favicon.ico"
    favicon_16 = "/img/favicon.ico"

    footercontent = "Site sponsored and supported by Theiagen Consulting LLC"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# change parameter to allow embedded html

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/staph-b/"


# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Training"
    weight = 1
    url  = "/training/"
[[menu.main]]
    name = "Resources"
    weight = 1
    url  = "/resources/"
[[menu.main]]
    name = "History"
    weight = 3
    url  = "/history/"
